---
# tasks file for roles/goofys_install
# go/binディレクトリを作成
- name: create go directory
  file:
    path: "{{ go_path }}/bin"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
    recurse: yes
  become: yes
# GOPATHを環境変数に設定
- name: go path set env
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    block: "export GOPATH={{ go_path }}\nexport PATH=${GOPATH}/bin:${PATH}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK GO"
# goofysダウンロード
- name: get goofys
  get_url:
    url: 'https://github.com/kahing/goofys/releases/latest/download/goofys'
    dest: "{{ go_path }}/bin/goofys"
    mode: "0755"
