---
- hosts: webservers
  roles:
    # タイムゾーン変更
    - role: set_timezone
      become: yes
    # yum パッケージインストール
    - role: yum_install
      become: yes
    # nginxインストール・起動
    - role: nginx_install
      become: yes
    # git config設定
    - git_config
    - myrole
