---
# アプリデプロイ先ディレクトリ作成
- name: create app base directory
  file:
    path: "{{ app_base_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
  become: yes
# github連携用の秘密鍵を~/.ssh配下へ転送
- name: export github private key
  copy:
    src: "~/.ssh/{{ github_ssh_private_key_file_name }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ github_ssh_private_key_file_name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0400"
# githubからアプリをクローン
- name: git clone application from github
  git:
    repo: git@github.com:artail2020/association_tutorial.git
    dest: "{{ app_base_path }}/{{ app_name }}"
    key_file: "{{ ansible_env.HOME }}/.ssh/{{ github_ssh_private_key_file_name }}"
    accept_hostkey: yes
