---
# rbenvインストール済であるかを確認
- name: rbenv installed check
  command: "{{ rbenv_path }}/bin/rbenv --version"
  register: rbenv_exists
  changed_when: false
  ignore_errors: yes
# git経由でrbenvインストール
- name: rbenv install from git
  git:
    repo: 'https://github.com/sstephenson/rbenv.git'
    dest: "{{ rbenv_path }}"
  become: yes
  when: rbenv_exists is failed
# 環境変数設定シェル作成
- name: create shell rbenv_env
  template:
    src: ruby_install/rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh
    mode: "0755"
  become: yes
  when: rbenv_exists is failed
# ruby-buildインストール
- name: ruby-build install from git
  git:
    repo: 'https://github.com/sstephenson/ruby-build.git'
    dest: "{{ rbenv_path }}/plugins/ruby-build"
  become: yes
  when: rbenv_exists is failed
# rbenv権限をSSHユーザーに変更
- name: change rbenv owner ssh user
  file:
    path: "{{ rbenv_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0775"
    recurse: yes
  become: yes
# rbenvインストール済バージョン確認
- name: ruby installed check
  command: "{{ rbenv_path }}/bin/rbenv versions"
  register: rbenv_versions
  changed_when: false
  ignore_errors: yes
# 所定のバージョンのrubyがなければインストール
- name: ruby install
  command: "{{ rbenv_path }}/bin/rbenv install {{ ruby_version }}"
  when: ruby_version not in rbenv_versions.stdout
  environment:
    CONFIGURE_OPTS: "--disable-install-doc --disable-install-rdoc --disable-install-capi"
# rubyグローバルバージョン確認
- name: ruby global version check
  command: "{{ rbenv_path }}/bin/rbenv global"
  register: ruby_global_version
# rubyグローバルバージョンを変更
- name: ruby global set
  command: "{{ rbenv_path }}/bin/rbenv global {{ ruby_version }}"
  when: ruby_version not in ruby_global_version.stdout
# Bundler・railsインストール
- name: install bundler and rails
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    executable: "{{ rbenv_path }}/shims/gem"
    user_install: no
  loop:
    - name: bundler
      version: "{{ bundler_version }}"
    - name: rails
      version: "{{ rails_version }}"
