---
- set_fact:
    ansible_facts:
      pkg_mgr: yum
# 必要パッケージのインストール
- name: install packages
  yum:
    name:
      - git
      - gcc
      - gcc-c++
      - make
      - openssl-devel
      - zlib-devel
      - readline-devel
      - mysql
      - mysql-devel
      - golang
      - fuse
      - yum-cron
    state: present
  become: yes
# yum-cron 設定変更
- name: replace yum-cron config
  replace:
    path: /etc/yum/yum-cron.conf
    regexp: '^apply_updates = no$'
    replace: 'apply_updates = yes'
  become: yes
# yum 自動更新をenabled
- name: yum-cron start and enabled
  service:
    name: yum-cron
    state: restarted
    enabled: yes
  become: yes
