---
# tasks file for roles/git_config
# git configにname,email設定
- name: git config setting
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - name: user.name
      value: "{{ git_user_name }}"
    - name: user.email
      value: "{{ git_user_email }}"
