---
# tasks file for roles/yum_install
- set_fact:
    ansible_facts:
      pkg_mgr: yum
# mariaDB削除
- name: uninstall mariaDB
  yum:
    name: mariadb-libs
    state: absent
# MySQL8.0 rpmインストール
- name: mysql8.0 rpm install
  yum:
    name: https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
    state: present
# MySQL アーカイブ用tmpディレクトリ作成
- name: create mysql tmp directory
  file:
    path: "{{ tmp_mysql_dir }}"
    state: directory
    owner: root
    group: root
    recurse: yes
# RDSと同一バージョンのアーカイブtarを解凍
- name: mysql archive tar unarchive
  unarchive:
    src: "https://downloads.mysql.com/archives/get/p/23/file/mysql-{{ hostvars[db_instance_name].engine_version }}-1.el7.x86_64.rpm-bundle.tar"
    dest: "{{ tmp_mysql_dir }}"
    remote_src: yes
# MySQL アーカイブrpmからインストール
- name: mysql archive rpm install
  yum:
    name:
      - "{{ tmp_mysql_dir }}/mysql-community-client-{{ hostvars[db_instance_name].engine_version }}-1.el7.x86_64.rpm"
      - "{{ tmp_mysql_dir }}/mysql-community-common-{{ hostvars[db_instance_name].engine_version }}-1.el7.x86_64.rpm"
      - "{{ tmp_mysql_dir }}/mysql-community-devel-{{ hostvars[db_instance_name].engine_version }}-1.el7.x86_64.rpm"
      - "{{ tmp_mysql_dir }}/mysql-community-libs-{{ hostvars[db_instance_name].engine_version }}-1.el7.x86_64.rpm"
    state: present
# 必要パッケージのインストール
- name: install packages
  yum:
    name:
      - git
      - gcc
      - gcc-c++
      - make
      - openssl-devel
      - zlib-devel
      - readline-devel
      - golang
      - fuse
      - yum-cron
    state: present
# yum-cron 設定変更
- name: replace yum-cron config
  replace:
    path: /etc/yum/yum-cron.conf
    regexp: '^apply_updates = no$'
    replace: 'apply_updates = yes'
# yum 自動更新をenabled
- name: yum-cron start and enabled
  service:
    name: yum-cron
    state: restarted
    enabled: yes
