---
# tasks file for roles/nginx_install
# nginxインストール可かチェック
- name: nginx package list in local
  yum:
    disablerepo: "*"
    list: nginx
  register: installed_pkgs
# nginxをyumでインストール可に変更
- name: nginx enable if not enabled
  command: amazon-linux-extras enable nginx1
  when: installed_pkgs.results | length == 0
# yumでnginxインストール
- name: yum install nginx
  yum:
    name: nginx
    state: present
# nginx自動起動をenabled
- name: nginx enabled
  service:
    name: nginx
    enabled: yes
  notify: nginx_restarted
